# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test ML' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test ML

  target 'Test MLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test MLUITests' do
    # Pods for testing
  end

end
